// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: adam_enum.proto

package com.boco.communication.socket.bean;

public final class AdamEnum {
  private AdamEnum() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code WEB_SERVICE_ENUM}
   */
  public enum WEB_SERVICE_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FA = 1;</code>
     *
     * <pre>
     * 4A
     * </pre>
     */
    FA(0, 1),
    /**
     * <code>SMP = 2;</code>
     *
     * <pre>
     * SMP
     * </pre>
     */
    SMP(1, 2),
    /**
     * <code>ISMP = 4;</code>
     *
     * <pre>
     * ISMP
     * </pre>
     */
    ISMP(2, 4),
    /**
     * <code>ADAM = 1024;</code>
     *
     * <pre>
     * ADAM
     * </pre>
     */
    ADAM(3, 1024),
    ;

    /**
     * <code>FA = 1;</code>
     *
     * <pre>
     * 4A
     * </pre>
     */
    public static final int FA_VALUE = 1;
    /**
     * <code>SMP = 2;</code>
     *
     * <pre>
     * SMP
     * </pre>
     */
    public static final int SMP_VALUE = 2;
    /**
     * <code>ISMP = 4;</code>
     *
     * <pre>
     * ISMP
     * </pre>
     */
    public static final int ISMP_VALUE = 4;
    /**
     * <code>ADAM = 1024;</code>
     *
     * <pre>
     * ADAM
     * </pre>
     */
    public static final int ADAM_VALUE = 1024;


    public final int getNumber() { return value; }

    public static WEB_SERVICE_ENUM valueOf(int value) {
      switch (value) {
        case 1: return FA;
        case 2: return SMP;
        case 4: return ISMP;
        case 1024: return ADAM;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<WEB_SERVICE_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<WEB_SERVICE_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<WEB_SERVICE_ENUM>() {
            public WEB_SERVICE_ENUM findValueByNumber(int number) {
              return WEB_SERVICE_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(0);
    }

    private static final WEB_SERVICE_ENUM[] VALUES = values();

    public static WEB_SERVICE_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private WEB_SERVICE_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:WEB_SERVICE_ENUM)
  }

  /**
   * Protobuf enum {@code ENGINE_TYPE_ENUM}
   *
   * <pre>
   *some engine type name with "D", to different from adam_protocol_enum
   * </pre>
   */
  public enum ENGINE_TYPE_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0, 0),
    /**
     * <code>NBA = 1;</code>
     */
    NBA(1, 1),
    /**
     * <code>SYSLOGD = 2;</code>
     */
    SYSLOGD(2, 2),
    /**
     * <code>FTPD = 3;</code>
     */
    FTPD(3, 3),
    /**
     * <code>TELNETD = 4;</code>
     */
    TELNETD(4, 4),
    /**
     * <code>JDBCD = 5;</code>
     */
    JDBCD(5, 5),
    /**
     * <code>GBA = 6;</code>
     */
    GBA(6, 6),
    /**
     * <code>CPS = 7;</code>
     */
    CPS(7, 7),
    /**
     * <code>IBA = 8;</code>
     */
    IBA(8, 8),
    /**
     * <code>FILTER = 9;</code>
     */
    FILTER(9, 9),
    /**
     * <code>NDE = 10;</code>
     */
    NDE(10, 10),
    /**
     * <code>ASCII = 11;</code>
     */
    ASCII(11, 11),
    /**
     * <code>PROBER = 12;</code>
     */
    PROBER(12, 12),
    /**
     * <code>WARDEN = 13;</code>
     */
    WARDEN(13, 13),
    /**
     * <code>PHENIX = 14;</code>
     */
    PHENIX(14, 14),
    /**
     * <code>EVE = 15;</code>
     *
     * <pre>
     * adam's portal
     * </pre>
     */
    EVE(15, 15),
    /**
     * <code>WBA = 16;</code>
     */
    WBA(16, 16),
    /**
     * <code>SNMPTRAP = 17;</code>
     */
    SNMPTRAP(17, 17),
    /**
     * <code>DETOUR = 18;</code>
     */
    DETOUR(18, 18),
    /**
     * <code>EVENT = 19;</code>
     */
    EVENT(19, 19),
    /**
     * <code>STATS = 20;</code>
     */
    STATS(20, 20),
    /**
     * <code>MERGER = 21;</code>
     */
    MERGER(21, 21),
    /**
     * <code>PB = 22;</code>
     */
    PB(22, 22),
    /**
     * <code>CBA = 23;</code>
     *
     * <pre>
     * for ISMP
     * </pre>
     */
    CBA(23, 23),
    /**
     * <code>ALERT = 24;</code>
     *
     * <pre>
     * for ISMP
     * </pre>
     */
    ALERT(24, 24),
    /**
     * <code>TRANSFER = 25;</code>
     *
     * <pre>
     * for CM
     * </pre>
     */
    TRANSFER(25, 25),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>NBA = 1;</code>
     */
    public static final int NBA_VALUE = 1;
    /**
     * <code>SYSLOGD = 2;</code>
     */
    public static final int SYSLOGD_VALUE = 2;
    /**
     * <code>FTPD = 3;</code>
     */
    public static final int FTPD_VALUE = 3;
    /**
     * <code>TELNETD = 4;</code>
     */
    public static final int TELNETD_VALUE = 4;
    /**
     * <code>JDBCD = 5;</code>
     */
    public static final int JDBCD_VALUE = 5;
    /**
     * <code>GBA = 6;</code>
     */
    public static final int GBA_VALUE = 6;
    /**
     * <code>CPS = 7;</code>
     */
    public static final int CPS_VALUE = 7;
    /**
     * <code>IBA = 8;</code>
     */
    public static final int IBA_VALUE = 8;
    /**
     * <code>FILTER = 9;</code>
     */
    public static final int FILTER_VALUE = 9;
    /**
     * <code>NDE = 10;</code>
     */
    public static final int NDE_VALUE = 10;
    /**
     * <code>ASCII = 11;</code>
     */
    public static final int ASCII_VALUE = 11;
    /**
     * <code>PROBER = 12;</code>
     */
    public static final int PROBER_VALUE = 12;
    /**
     * <code>WARDEN = 13;</code>
     */
    public static final int WARDEN_VALUE = 13;
    /**
     * <code>PHENIX = 14;</code>
     */
    public static final int PHENIX_VALUE = 14;
    /**
     * <code>EVE = 15;</code>
     *
     * <pre>
     * adam's portal
     * </pre>
     */
    public static final int EVE_VALUE = 15;
    /**
     * <code>WBA = 16;</code>
     */
    public static final int WBA_VALUE = 16;
    /**
     * <code>SNMPTRAP = 17;</code>
     */
    public static final int SNMPTRAP_VALUE = 17;
    /**
     * <code>DETOUR = 18;</code>
     */
    public static final int DETOUR_VALUE = 18;
    /**
     * <code>EVENT = 19;</code>
     */
    public static final int EVENT_VALUE = 19;
    /**
     * <code>STATS = 20;</code>
     */
    public static final int STATS_VALUE = 20;
    /**
     * <code>MERGER = 21;</code>
     */
    public static final int MERGER_VALUE = 21;
    /**
     * <code>PB = 22;</code>
     */
    public static final int PB_VALUE = 22;
    /**
     * <code>CBA = 23;</code>
     *
     * <pre>
     * for ISMP
     * </pre>
     */
    public static final int CBA_VALUE = 23;
    /**
     * <code>ALERT = 24;</code>
     *
     * <pre>
     * for ISMP
     * </pre>
     */
    public static final int ALERT_VALUE = 24;
    /**
     * <code>TRANSFER = 25;</code>
     *
     * <pre>
     * for CM
     * </pre>
     */
    public static final int TRANSFER_VALUE = 25;


    public final int getNumber() { return value; }

    public static ENGINE_TYPE_ENUM valueOf(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return NBA;
        case 2: return SYSLOGD;
        case 3: return FTPD;
        case 4: return TELNETD;
        case 5: return JDBCD;
        case 6: return GBA;
        case 7: return CPS;
        case 8: return IBA;
        case 9: return FILTER;
        case 10: return NDE;
        case 11: return ASCII;
        case 12: return PROBER;
        case 13: return WARDEN;
        case 14: return PHENIX;
        case 15: return EVE;
        case 16: return WBA;
        case 17: return SNMPTRAP;
        case 18: return DETOUR;
        case 19: return EVENT;
        case 20: return STATS;
        case 21: return MERGER;
        case 22: return PB;
        case 23: return CBA;
        case 24: return ALERT;
        case 25: return TRANSFER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ENGINE_TYPE_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ENGINE_TYPE_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ENGINE_TYPE_ENUM>() {
            public ENGINE_TYPE_ENUM findValueByNumber(int number) {
              return ENGINE_TYPE_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(1);
    }

    private static final ENGINE_TYPE_ENUM[] VALUES = values();

    public static ENGINE_TYPE_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ENGINE_TYPE_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ENGINE_TYPE_ENUM)
  }

  /**
   * Protobuf enum {@code ADAM_PROTOCOL_ENUM}
   */
  public enum ADAM_PROTOCOL_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SSH1 = 1;</code>
     */
    SSH1(0, 1),
    /**
     * <code>SSH2 = 2;</code>
     */
    SSH2(1, 2),
    /**
     * <code>TELNET = 4;</code>
     */
    TELNET(2, 4),
    /**
     * <code>FTP = 8;</code>
     */
    FTP(3, 8),
    /**
     * <code>SFTP = 16;</code>
     */
    SFTP(4, 16),
    /**
     * <code>HTTP = 32;</code>
     */
    HTTP(5, 32),
    /**
     * <code>HTTPS = 64;</code>
     */
    HTTPS(6, 64),
    ;

    /**
     * <code>SSH1 = 1;</code>
     */
    public static final int SSH1_VALUE = 1;
    /**
     * <code>SSH2 = 2;</code>
     */
    public static final int SSH2_VALUE = 2;
    /**
     * <code>TELNET = 4;</code>
     */
    public static final int TELNET_VALUE = 4;
    /**
     * <code>FTP = 8;</code>
     */
    public static final int FTP_VALUE = 8;
    /**
     * <code>SFTP = 16;</code>
     */
    public static final int SFTP_VALUE = 16;
    /**
     * <code>HTTP = 32;</code>
     */
    public static final int HTTP_VALUE = 32;
    /**
     * <code>HTTPS = 64;</code>
     */
    public static final int HTTPS_VALUE = 64;


    public final int getNumber() { return value; }

    public static ADAM_PROTOCOL_ENUM valueOf(int value) {
      switch (value) {
        case 1: return SSH1;
        case 2: return SSH2;
        case 4: return TELNET;
        case 8: return FTP;
        case 16: return SFTP;
        case 32: return HTTP;
        case 64: return HTTPS;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ADAM_PROTOCOL_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ADAM_PROTOCOL_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ADAM_PROTOCOL_ENUM>() {
            public ADAM_PROTOCOL_ENUM findValueByNumber(int number) {
              return ADAM_PROTOCOL_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(2);
    }

    private static final ADAM_PROTOCOL_ENUM[] VALUES = values();

    public static ADAM_PROTOCOL_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ADAM_PROTOCOL_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ADAM_PROTOCOL_ENUM)
  }

  /**
   * Protobuf enum {@code ADAM_LOG_LEVEL_ENUM}
   */
  public enum ADAM_LOG_LEVEL_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>KERN_EMERG = 1;</code>
     *
     * <pre>
     * 紧�? 
     * </pre>
     */
    KERN_EMERG(0, 1),
    /**
     * <code>KERN_ALERT = 2;</code>
     *
     * <pre>
     * 危�?
     * </pre>
     */
    KERN_ALERT(1, 2),
    /**
     * <code>KERN_CRIT = 3;</code>
     *
     * <pre>
     * 严重
     * </pre>
     */
    KERN_CRIT(2, 3),
    /**
     * <code>KERN_ERR = 4;</code>
     *
     * <pre>
     * 错误
     * </pre>
     */
    KERN_ERR(3, 4),
    /**
     * <code>KERN_WARNING = 5;</code>
     *
     * <pre>
     * 警告
     * </pre>
     */
    KERN_WARNING(4, 5),
    /**
     * <code>KERN_NOTICE = 6;</code>
     *
     * <pre>
     * 报告
     * </pre>
     */
    KERN_NOTICE(5, 6),
    /**
     * <code>KERN_INFO = 7;</code>
     *
     * <pre>
     * 提示
     * </pre>
     */
    KERN_INFO(6, 7),
    /**
     * <code>KERN_DEBUG = 8;</code>
     *
     * <pre>
     * 调试�?     * </pre>
     */
    KERN_DEBUG(7, 8),
    ;

    /**
     * <code>KERN_EMERG = 1;</code>
     *
     * <pre>
     * 紧�? 
     * </pre>
     */
    public static final int KERN_EMERG_VALUE = 1;
    /**
     * <code>KERN_ALERT = 2;</code>
     *
     * <pre>
     * 危�?
     * </pre>
     */
    public static final int KERN_ALERT_VALUE = 2;
    /**
     * <code>KERN_CRIT = 3;</code>
     *
     * <pre>
     * 严重
     * </pre>
     */
    public static final int KERN_CRIT_VALUE = 3;
    /**
     * <code>KERN_ERR = 4;</code>
     *
     * <pre>
     * 错误
     * </pre>
     */
    public static final int KERN_ERR_VALUE = 4;
    /**
     * <code>KERN_WARNING = 5;</code>
     *
     * <pre>
     * 警告
     * </pre>
     */
    public static final int KERN_WARNING_VALUE = 5;
    /**
     * <code>KERN_NOTICE = 6;</code>
     *
     * <pre>
     * 报告
     * </pre>
     */
    public static final int KERN_NOTICE_VALUE = 6;
    /**
     * <code>KERN_INFO = 7;</code>
     *
     * <pre>
     * 提示
     * </pre>
     */
    public static final int KERN_INFO_VALUE = 7;
    /**
     * <code>KERN_DEBUG = 8;</code>
     *
     * <pre>
     * 调试�?     * </pre>
     */
    public static final int KERN_DEBUG_VALUE = 8;


    public final int getNumber() { return value; }

    public static ADAM_LOG_LEVEL_ENUM valueOf(int value) {
      switch (value) {
        case 1: return KERN_EMERG;
        case 2: return KERN_ALERT;
        case 3: return KERN_CRIT;
        case 4: return KERN_ERR;
        case 5: return KERN_WARNING;
        case 6: return KERN_NOTICE;
        case 7: return KERN_INFO;
        case 8: return KERN_DEBUG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ADAM_LOG_LEVEL_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ADAM_LOG_LEVEL_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ADAM_LOG_LEVEL_ENUM>() {
            public ADAM_LOG_LEVEL_ENUM findValueByNumber(int number) {
              return ADAM_LOG_LEVEL_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(3);
    }

    private static final ADAM_LOG_LEVEL_ENUM[] VALUES = values();

    public static ADAM_LOG_LEVEL_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ADAM_LOG_LEVEL_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ADAM_LOG_LEVEL_ENUM)
  }

  /**
   * Protobuf enum {@code ADAM_ORDER_TYPE_ENUM}
   */
  public enum ADAM_ORDER_TYPE_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ORDER_SEQUENCE = 1;</code>
     */
    ORDER_SEQUENCE(0, 1),
    /**
     * <code>ORDER_SCRIPT = 2;</code>
     */
    ORDER_SCRIPT(1, 2),
    /**
     * <code>ORDER_HTTP = 3;</code>
     */
    ORDER_HTTP(2, 3),
    /**
     * <code>ORDER_HTTPS = 4;</code>
     */
    ORDER_HTTPS(3, 4),
    /**
     * <code>ORDER_JDBC = 5;</code>
     */
    ORDER_JDBC(4, 5),
    ;

    /**
     * <code>ORDER_SEQUENCE = 1;</code>
     */
    public static final int ORDER_SEQUENCE_VALUE = 1;
    /**
     * <code>ORDER_SCRIPT = 2;</code>
     */
    public static final int ORDER_SCRIPT_VALUE = 2;
    /**
     * <code>ORDER_HTTP = 3;</code>
     */
    public static final int ORDER_HTTP_VALUE = 3;
    /**
     * <code>ORDER_HTTPS = 4;</code>
     */
    public static final int ORDER_HTTPS_VALUE = 4;
    /**
     * <code>ORDER_JDBC = 5;</code>
     */
    public static final int ORDER_JDBC_VALUE = 5;


    public final int getNumber() { return value; }

    public static ADAM_ORDER_TYPE_ENUM valueOf(int value) {
      switch (value) {
        case 1: return ORDER_SEQUENCE;
        case 2: return ORDER_SCRIPT;
        case 3: return ORDER_HTTP;
        case 4: return ORDER_HTTPS;
        case 5: return ORDER_JDBC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ADAM_ORDER_TYPE_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ADAM_ORDER_TYPE_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ADAM_ORDER_TYPE_ENUM>() {
            public ADAM_ORDER_TYPE_ENUM findValueByNumber(int number) {
              return ADAM_ORDER_TYPE_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(4);
    }

    private static final ADAM_ORDER_TYPE_ENUM[] VALUES = values();

    public static ADAM_ORDER_TYPE_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ADAM_ORDER_TYPE_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ADAM_ORDER_TYPE_ENUM)
  }

  /**
   * Protobuf enum {@code ADAM_ENCODING_ENUM}
   */
  public enum ADAM_ENCODING_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADAM_ASCII = 1;</code>
     */
    ADAM_ASCII(0, 1),
    /**
     * <code>ADAM_UTF_8 = 2;</code>
     */
    ADAM_UTF_8(1, 2),
    /**
     * <code>ADAM_GBK = 3;</code>
     */
    ADAM_GBK(2, 3),
    ;

    /**
     * <code>ADAM_ASCII = 1;</code>
     */
    public static final int ADAM_ASCII_VALUE = 1;
    /**
     * <code>ADAM_UTF_8 = 2;</code>
     */
    public static final int ADAM_UTF_8_VALUE = 2;
    /**
     * <code>ADAM_GBK = 3;</code>
     */
    public static final int ADAM_GBK_VALUE = 3;


    public final int getNumber() { return value; }

    public static ADAM_ENCODING_ENUM valueOf(int value) {
      switch (value) {
        case 1: return ADAM_ASCII;
        case 2: return ADAM_UTF_8;
        case 3: return ADAM_GBK;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ADAM_ENCODING_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ADAM_ENCODING_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ADAM_ENCODING_ENUM>() {
            public ADAM_ENCODING_ENUM findValueByNumber(int number) {
              return ADAM_ENCODING_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(5);
    }

    private static final ADAM_ENCODING_ENUM[] VALUES = values();

    public static ADAM_ENCODING_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ADAM_ENCODING_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ADAM_ENCODING_ENUM)
  }

  /**
   * Protobuf enum {@code ANA_POLICY_TYPE}
   */
  public enum ANA_POLICY_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>FILTER_POLICY = 1;</code>
     *
     * <pre>
     * filter policy
     * </pre>
     */
    FILTER_POLICY(0, 1),
    /**
     * <code>SUBJECT_POLICY = 2;</code>
     *
     * <pre>
     * subject policy
     * </pre>
     */
    SUBJECT_POLICY(1, 2),
    /**
     * <code>EVENT_POLICY = 3;</code>
     *
     * <pre>
     * event analysis policy
     * </pre>
     */
    EVENT_POLICY(2, 3),
    /**
     * <code>STATS_POLICY = 4;</code>
     *
     * <pre>
     * statistic analysis policy
     * </pre>
     */
    STATS_POLICY(3, 4),
    /**
     * <code>DETOUR_POLICY = 5;</code>
     *
     * <pre>
     * detour policy
     * </pre>
     */
    DETOUR_POLICY(4, 5),
    /**
     * <code>MERGER_POLICY = 6;</code>
     *
     * <pre>
     * merger policy
     * </pre>
     */
    MERGER_POLICY(5, 6),
    /**
     * <code>NBA_ENCODE_POLICY = 10;</code>
     */
    NBA_ENCODE_POLICY(6, 10),
    /**
     * <code>GBA_ENCODE_POLICY = 11;</code>
     */
    GBA_ENCODE_POLICY(7, 11),
    /**
     * <code>SYSLOG_ENCODE_POLICY = 12;</code>
     */
    SYSLOG_ENCODE_POLICY(8, 12),
    /**
     * <code>FTP_ENCODE_POLICY = 13;</code>
     */
    FTP_ENCODE_POLICY(9, 13),
    /**
     * <code>TELNET_ENCODE_POLICY = 14;</code>
     */
    TELNET_ENCODE_POLICY(10, 14),
    /**
     * <code>JDBC_ENCODE_POLICY = 15;</code>
     */
    JDBC_ENCODE_POLICY(11, 15),
    ;

    /**
     * <code>FILTER_POLICY = 1;</code>
     *
     * <pre>
     * filter policy
     * </pre>
     */
    public static final int FILTER_POLICY_VALUE = 1;
    /**
     * <code>SUBJECT_POLICY = 2;</code>
     *
     * <pre>
     * subject policy
     * </pre>
     */
    public static final int SUBJECT_POLICY_VALUE = 2;
    /**
     * <code>EVENT_POLICY = 3;</code>
     *
     * <pre>
     * event analysis policy
     * </pre>
     */
    public static final int EVENT_POLICY_VALUE = 3;
    /**
     * <code>STATS_POLICY = 4;</code>
     *
     * <pre>
     * statistic analysis policy
     * </pre>
     */
    public static final int STATS_POLICY_VALUE = 4;
    /**
     * <code>DETOUR_POLICY = 5;</code>
     *
     * <pre>
     * detour policy
     * </pre>
     */
    public static final int DETOUR_POLICY_VALUE = 5;
    /**
     * <code>MERGER_POLICY = 6;</code>
     *
     * <pre>
     * merger policy
     * </pre>
     */
    public static final int MERGER_POLICY_VALUE = 6;
    /**
     * <code>NBA_ENCODE_POLICY = 10;</code>
     */
    public static final int NBA_ENCODE_POLICY_VALUE = 10;
    /**
     * <code>GBA_ENCODE_POLICY = 11;</code>
     */
    public static final int GBA_ENCODE_POLICY_VALUE = 11;
    /**
     * <code>SYSLOG_ENCODE_POLICY = 12;</code>
     */
    public static final int SYSLOG_ENCODE_POLICY_VALUE = 12;
    /**
     * <code>FTP_ENCODE_POLICY = 13;</code>
     */
    public static final int FTP_ENCODE_POLICY_VALUE = 13;
    /**
     * <code>TELNET_ENCODE_POLICY = 14;</code>
     */
    public static final int TELNET_ENCODE_POLICY_VALUE = 14;
    /**
     * <code>JDBC_ENCODE_POLICY = 15;</code>
     */
    public static final int JDBC_ENCODE_POLICY_VALUE = 15;


    public final int getNumber() { return value; }

    public static ANA_POLICY_TYPE valueOf(int value) {
      switch (value) {
        case 1: return FILTER_POLICY;
        case 2: return SUBJECT_POLICY;
        case 3: return EVENT_POLICY;
        case 4: return STATS_POLICY;
        case 5: return DETOUR_POLICY;
        case 6: return MERGER_POLICY;
        case 10: return NBA_ENCODE_POLICY;
        case 11: return GBA_ENCODE_POLICY;
        case 12: return SYSLOG_ENCODE_POLICY;
        case 13: return FTP_ENCODE_POLICY;
        case 14: return TELNET_ENCODE_POLICY;
        case 15: return JDBC_ENCODE_POLICY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ANA_POLICY_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ANA_POLICY_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ANA_POLICY_TYPE>() {
            public ANA_POLICY_TYPE findValueByNumber(int number) {
              return ANA_POLICY_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(6);
    }

    private static final ANA_POLICY_TYPE[] VALUES = values();

    public static ANA_POLICY_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ANA_POLICY_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ANA_POLICY_TYPE)
  }

  /**
   * Protobuf enum {@code DIRECTION}
   */
  public enum DIRECTION
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>REQUEST = 0;</code>
     */
    REQUEST(0, 0),
    /**
     * <code>RESPONSE = 1;</code>
     */
    RESPONSE(1, 1),
    ;

    /**
     * <code>REQUEST = 0;</code>
     */
    public static final int REQUEST_VALUE = 0;
    /**
     * <code>RESPONSE = 1;</code>
     */
    public static final int RESPONSE_VALUE = 1;


    public final int getNumber() { return value; }

    public static DIRECTION valueOf(int value) {
      switch (value) {
        case 0: return REQUEST;
        case 1: return RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DIRECTION>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<DIRECTION>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DIRECTION>() {
            public DIRECTION findValueByNumber(int number) {
              return DIRECTION.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(7);
    }

    private static final DIRECTION[] VALUES = values();

    public static DIRECTION valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private DIRECTION(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:DIRECTION)
  }

  /**
   * Protobuf enum {@code ADAM_HEAD_TYPE_ENUM}
   *
   * <pre>
   ** 打包时，缓冲区的头部�?LENGTH(4BYTES) + ADAM_HEAD_TYPE_ENUM(4BYTES)
   * </pre>
   */
  public enum ADAM_HEAD_TYPE_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>WEB_2_PROBER_REQUEST = 1;</code>
     *
     * <pre>
     * for WEB --&gt; PROBER [ 1, 50]
     * may be need to add other request type
     * </pre>
     */
    WEB_2_PROBER_REQUEST(0, 1),
    /**
     * <code>WEB_2_PROBER_REQUEST_VERIFY = 2;</code>
     */
    WEB_2_PROBER_REQUEST_VERIFY(1, 2),
    /**
     * <code>WEB_2_PROBER_RESPONSE_VERIFY = 3;</code>
     */
    WEB_2_PROBER_RESPONSE_VERIFY(2, 3),
    /**
     * <code>WEB_2_PROBER_REQUEST_AGAIN = 4;</code>
     */
    WEB_2_PROBER_REQUEST_AGAIN(3, 4),
    /**
     * <code>PROBER_2_WEB_REQUEST_ACCEPT = 51;</code>
     *
     * <pre>
     * for PROBER --&gt; WEB [51, 100]
     * </pre>
     */
    PROBER_2_WEB_REQUEST_ACCEPT(4, 51),
    /**
     * <code>PROBER_2_WEB_RESPONSE = 52;</code>
     */
    PROBER_2_WEB_RESPONSE(5, 52),
    /**
     * <code>PROBER_2_WEB_REALTIME_RESPONSE = 53;</code>
     */
    PROBER_2_WEB_REALTIME_RESPONSE(6, 53),
    /**
     * <code>WEB_2_PHENIX_REGISTER = 201;</code>
     *
     * <pre>
     * for PHENIX[201, 300] 
     * </pre>
     */
    WEB_2_PHENIX_REGISTER(7, 201),
    /**
     * <code>PHENIX_2_WEB_REGISTER_RESPONSE = 202;</code>
     *
     * <pre>
     * phenix -&gt; web : first info
     * </pre>
     */
    PHENIX_2_WEB_REGISTER_RESPONSE(8, 202),
    /**
     * <code>ENGINE_2_PHENIX_PROCESS_UPDATE = 203;</code>
     *
     * <pre>
     *engine -&gt; phenix: process update
     * </pre>
     */
    ENGINE_2_PHENIX_PROCESS_UPDATE(9, 203),
    /**
     * <code>PHENIX_2_WEB_PROCESS_UPDATE = 204;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    PHENIX_2_WEB_PROCESS_UPDATE(10, 204),
    /**
     * <code>WARDEN_2_PHENIX_HOST_UPDATE = 205;</code>
     *
     * <pre>
     *warden -&gt; phenix: host update
     * </pre>
     */
    WARDEN_2_PHENIX_HOST_UPDATE(11, 205),
    /**
     * <code>PHENIX_2_WEB_HOST_UPDATE = 206;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    PHENIX_2_WEB_HOST_UPDATE(12, 206),
    /**
     * <code>PHENIX_2_WEB_HOST_UNAVAILABLE = 221;</code>
     *
     * <pre>
     *phenix -&gt; web: host unavailable
     * </pre>
     */
    PHENIX_2_WEB_HOST_UNAVAILABLE(13, 221),
    /**
     * <code>PHENIX_2_WEB_WARDEN_DISCONN = 222;</code>
     *
     * <pre>
     *phenix -&gt; web: warden conn failed
     * </pre>
     */
    PHENIX_2_WEB_WARDEN_DISCONN(14, 222),
    /**
     * <code>PHENIX_2_WARDEN_CHECK = 223;</code>
     *
     * <pre>
     *phenix -&gt; warden
     * </pre>
     */
    PHENIX_2_WARDEN_CHECK(15, 223),
    /**
     * <code>WARDEN_2_PHENIX_CHECK_RESPONSE = 224;</code>
     *
     * <pre>
     *warden -&gt; phenix: check result
     * </pre>
     */
    WARDEN_2_PHENIX_CHECK_RESPONSE(16, 224),
    /**
     * <code>PHENIX_2_WEB_PROCESS_NOTIFY = 225;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    PHENIX_2_WEB_PROCESS_NOTIFY(17, 225),
    /**
     * <code>WEB_2_PHENIX_CMD_REQUEST = 240;</code>
     *
     * <pre>
     *web -&gt; phenix: service start, stop, uninstall
     * </pre>
     */
    WEB_2_PHENIX_CMD_REQUEST(18, 240),
    /**
     * <code>PHENIX_2_WARDEN_CMD_REQUEST = 241;</code>
     *
     * <pre>
     *phenix -&gt; warden
     * </pre>
     */
    PHENIX_2_WARDEN_CMD_REQUEST(19, 241),
    /**
     * <code>WARDEN_2_PHENIX_CMD_RESPONSE = 242;</code>
     *
     * <pre>
     *warden -&gt; phenix: cmd result
     * </pre>
     */
    WARDEN_2_PHENIX_CMD_RESPONSE(20, 242),
    /**
     * <code>PHENIX_2_WEB_CMD_RESPONSE = 243;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    PHENIX_2_WEB_CMD_RESPONSE(21, 243),
    /**
     * <code>WEB_2_PHENIX_POLICY_RELEASE = 250;</code>
     *
     * <pre>
     *web -&gt; phenix: release policy
     * </pre>
     */
    WEB_2_PHENIX_POLICY_RELEASE(22, 250),
    /**
     * <code>PHENIX_2_WARDEN_POLICY_RELEASE = 251;</code>
     *
     * <pre>
     *phenix -&gt; warden
     * </pre>
     */
    PHENIX_2_WARDEN_POLICY_RELEASE(23, 251),
    /**
     * <code>WARDEN_2_PHENIX_POLICY_RELEASE_RESPONSE = 252;</code>
     *
     * <pre>
     *warden -&gt; phenix: release result
     * </pre>
     */
    WARDEN_2_PHENIX_POLICY_RELEASE_RESPONSE(24, 252),
    /**
     * <code>PHENIX_2_WEB_POLICY_RELEASE_RESPONSE = 253;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    PHENIX_2_WEB_POLICY_RELEASE_RESPONSE(25, 253),
    /**
     * <code>WEB_CHECK_ENGINE_EXIST_REQUEST = 254;</code>
     *
     * <pre>
     *web --&gt; warden: request to check engine  whether exist 
     * </pre>
     */
    WEB_CHECK_ENGINE_EXIST_REQUEST(26, 254),
    /**
     * <code>WEB_CHECK_ENGINE_EXIST_RESPONSE = 255;</code>
     *
     * <pre>
     *warden --&gt; web: response to check engine  whether exist
     * </pre>
     */
    WEB_CHECK_ENGINE_EXIST_RESPONSE(27, 255),
    /**
     * <code>TRANSFER_2_PROBER_REQUEST = 501;</code>
     *
     * <pre>
     * FOR TRANSFER --&gt; PROBER
     * </pre>
     */
    TRANSFER_2_PROBER_REQUEST(28, 501),
    /**
     * <code>PROBER_2_TRANSFER_RESPONSE = 502;</code>
     *
     * <pre>
     * prober responses for transfer's request
     * </pre>
     */
    PROBER_2_TRANSFER_RESPONSE(29, 502),
    /**
     * <code>ADAM_USERSESSION = 1001;</code>
     *
     * <pre>
     *&#47;/////////////////////////////////////////////////////
     * for GATHER AND ANALYSIS ENGINE [1001, ~)
     * </pre>
     */
    ADAM_USERSESSION(30, 1001),
    /**
     * <code>ADAM_STREAM = 1002;</code>
     *
     * <pre>
     *t_stream, 月表
     * </pre>
     */
    ADAM_STREAM(31, 1002),
    /**
     * <code>ADAM_OPER = 1003;</code>
     *
     * <pre>
     *t_oper, 日表
     * </pre>
     */
    ADAM_OPER(32, 1003),
    /**
     * <code>ADAM_TREASURY = 1004;</code>
     *
     * <pre>
     *t_treasury_log, 月表
     * </pre>
     */
    ADAM_TREASURY(33, 1004),
    /**
     * <code>ADAM_TREAOPER = 1005;</code>
     *
     * <pre>
     *t_treasury_oper, 日表
     * </pre>
     */
    ADAM_TREAOPER(34, 1005),
    /**
     * <code>ADAM_HBA = 1006;</code>
     *
     * <pre>
     *t_hba_log, 日表
     * </pre>
     */
    ADAM_HBA(35, 1006),
    /**
     * <code>ADAM_CPSPROXY = 1007;</code>
     *
     * <pre>
     *t_proxy_log, 日表
     * </pre>
     */
    ADAM_CPSPROXY(36, 1007),
    /**
     * <code>ADAM_WBA = 1008;</code>
     *
     * <pre>
     *t_wba_log, 日表
     * </pre>
     */
    ADAM_WBA(37, 1008),
    /**
     * <code>ADAM_WBA_SESS = 1009;</code>
     *
     * <pre>
     *t_wba_sess, 月表
     * </pre>
     */
    ADAM_WBA_SESS(38, 1009),
    /**
     * <code>ADAM_EVE = 1050;</code>
     *
     * <pre>
     *t_eve_log, 日表
     * </pre>
     */
    ADAM_EVE(39, 1050),
    /**
     * <code>ADAM_IAM = 1051;</code>
     *
     * <pre>
     *t_iam_log, 日表
     * </pre>
     */
    ADAM_IAM(40, 1051),
    /**
     * <code>ADAM_SMP = 1052;</code>
     *
     * <pre>
     *t_smp_log, 日表
     * </pre>
     */
    ADAM_SMP(41, 1052),
    /**
     * <code>ADAM_DETOUR = 1055;</code>
     *
     * <pre>
     *t_detour_log, 日表
     * </pre>
     */
    ADAM_DETOUR(42, 1055),
    /**
     * <code>ADAM_EVENT = 1061;</code>
     *
     * <pre>
     *t_event_log, 日表
     * </pre>
     */
    ADAM_EVENT(43, 1061),
    /**
     * <code>ADAM_KEYANA = 1062;</code>
     *
     * <pre>
     *t_keyana_log, 月表
     * </pre>
     */
    ADAM_KEYANA(44, 1062),
    /**
     * <code>ADAM_STATANA = 1063;</code>
     *
     * <pre>
     *t_statsana_log, 月表
     * </pre>
     */
    ADAM_STATANA(45, 1063),
    /**
     * <code>ADAM_SUBJECT = 1064;</code>
     *
     * <pre>
     *专题分拣日志，日志中指定入库的表�?     * </pre>
     */
    ADAM_SUBJECT(46, 1064),
    /**
     * <code>ADAM_DETOURANA = 1065;</code>
     *
     * <pre>
     *t_detourana_log, 日表
     * </pre>
     */
    ADAM_DETOURANA(47, 1065),
    /**
     * <code>ADAM_WARN = 1066;</code>
     *
     * <pre>
     *t_warn_log, 月表
     * </pre>
     */
    ADAM_WARN(48, 1066),
    /**
     * <code>ADAM_MERGER = 1067;</code>
     *
     * <pre>
     *t_merge_log 日志，归并日志表
     * </pre>
     */
    ADAM_MERGER(49, 1067),
    /**
     * <code>ADAM_MERGER_RELATION = 1068;</code>
     *
     * <pre>
     *t_merge_format_relation_log 日表，归并日志与标准化日志映射表
     * </pre>
     */
    ADAM_MERGER_RELATION(50, 1068),
    /**
     * <code>ADAM_STATS_RELATION = 1069;</code>
     *
     * <pre>
     *t_alarm_format_relation_log 日表，实时统计分析告警与标准化日志映射表
     * </pre>
     */
    ADAM_STATS_RELATION(51, 1069),
    /**
     * <code>ADAM_FORWARD = 1071;</code>
     *
     * <pre>
     *同步用，不存日志到库�?     * </pre>
     */
    ADAM_FORWARD(52, 1071),
    ;

    /**
     * <code>WEB_2_PROBER_REQUEST = 1;</code>
     *
     * <pre>
     * for WEB --&gt; PROBER [ 1, 50]
     * may be need to add other request type
     * </pre>
     */
    public static final int WEB_2_PROBER_REQUEST_VALUE = 1;
    /**
     * <code>WEB_2_PROBER_REQUEST_VERIFY = 2;</code>
     */
    public static final int WEB_2_PROBER_REQUEST_VERIFY_VALUE = 2;
    /**
     * <code>WEB_2_PROBER_RESPONSE_VERIFY = 3;</code>
     */
    public static final int WEB_2_PROBER_RESPONSE_VERIFY_VALUE = 3;
    /**
     * <code>WEB_2_PROBER_REQUEST_AGAIN = 4;</code>
     */
    public static final int WEB_2_PROBER_REQUEST_AGAIN_VALUE = 4;
    /**
     * <code>PROBER_2_WEB_REQUEST_ACCEPT = 51;</code>
     *
     * <pre>
     * for PROBER --&gt; WEB [51, 100]
     * </pre>
     */
    public static final int PROBER_2_WEB_REQUEST_ACCEPT_VALUE = 51;
    /**
     * <code>PROBER_2_WEB_RESPONSE = 52;</code>
     */
    public static final int PROBER_2_WEB_RESPONSE_VALUE = 52;
    /**
     * <code>PROBER_2_WEB_REALTIME_RESPONSE = 53;</code>
     */
    public static final int PROBER_2_WEB_REALTIME_RESPONSE_VALUE = 53;
    /**
     * <code>WEB_2_PHENIX_REGISTER = 201;</code>
     *
     * <pre>
     * for PHENIX[201, 300] 
     * </pre>
     */
    public static final int WEB_2_PHENIX_REGISTER_VALUE = 201;
    /**
     * <code>PHENIX_2_WEB_REGISTER_RESPONSE = 202;</code>
     *
     * <pre>
     * phenix -&gt; web : first info
     * </pre>
     */
    public static final int PHENIX_2_WEB_REGISTER_RESPONSE_VALUE = 202;
    /**
     * <code>ENGINE_2_PHENIX_PROCESS_UPDATE = 203;</code>
     *
     * <pre>
     *engine -&gt; phenix: process update
     * </pre>
     */
    public static final int ENGINE_2_PHENIX_PROCESS_UPDATE_VALUE = 203;
    /**
     * <code>PHENIX_2_WEB_PROCESS_UPDATE = 204;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    public static final int PHENIX_2_WEB_PROCESS_UPDATE_VALUE = 204;
    /**
     * <code>WARDEN_2_PHENIX_HOST_UPDATE = 205;</code>
     *
     * <pre>
     *warden -&gt; phenix: host update
     * </pre>
     */
    public static final int WARDEN_2_PHENIX_HOST_UPDATE_VALUE = 205;
    /**
     * <code>PHENIX_2_WEB_HOST_UPDATE = 206;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    public static final int PHENIX_2_WEB_HOST_UPDATE_VALUE = 206;
    /**
     * <code>PHENIX_2_WEB_HOST_UNAVAILABLE = 221;</code>
     *
     * <pre>
     *phenix -&gt; web: host unavailable
     * </pre>
     */
    public static final int PHENIX_2_WEB_HOST_UNAVAILABLE_VALUE = 221;
    /**
     * <code>PHENIX_2_WEB_WARDEN_DISCONN = 222;</code>
     *
     * <pre>
     *phenix -&gt; web: warden conn failed
     * </pre>
     */
    public static final int PHENIX_2_WEB_WARDEN_DISCONN_VALUE = 222;
    /**
     * <code>PHENIX_2_WARDEN_CHECK = 223;</code>
     *
     * <pre>
     *phenix -&gt; warden
     * </pre>
     */
    public static final int PHENIX_2_WARDEN_CHECK_VALUE = 223;
    /**
     * <code>WARDEN_2_PHENIX_CHECK_RESPONSE = 224;</code>
     *
     * <pre>
     *warden -&gt; phenix: check result
     * </pre>
     */
    public static final int WARDEN_2_PHENIX_CHECK_RESPONSE_VALUE = 224;
    /**
     * <code>PHENIX_2_WEB_PROCESS_NOTIFY = 225;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    public static final int PHENIX_2_WEB_PROCESS_NOTIFY_VALUE = 225;
    /**
     * <code>WEB_2_PHENIX_CMD_REQUEST = 240;</code>
     *
     * <pre>
     *web -&gt; phenix: service start, stop, uninstall
     * </pre>
     */
    public static final int WEB_2_PHENIX_CMD_REQUEST_VALUE = 240;
    /**
     * <code>PHENIX_2_WARDEN_CMD_REQUEST = 241;</code>
     *
     * <pre>
     *phenix -&gt; warden
     * </pre>
     */
    public static final int PHENIX_2_WARDEN_CMD_REQUEST_VALUE = 241;
    /**
     * <code>WARDEN_2_PHENIX_CMD_RESPONSE = 242;</code>
     *
     * <pre>
     *warden -&gt; phenix: cmd result
     * </pre>
     */
    public static final int WARDEN_2_PHENIX_CMD_RESPONSE_VALUE = 242;
    /**
     * <code>PHENIX_2_WEB_CMD_RESPONSE = 243;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    public static final int PHENIX_2_WEB_CMD_RESPONSE_VALUE = 243;
    /**
     * <code>WEB_2_PHENIX_POLICY_RELEASE = 250;</code>
     *
     * <pre>
     *web -&gt; phenix: release policy
     * </pre>
     */
    public static final int WEB_2_PHENIX_POLICY_RELEASE_VALUE = 250;
    /**
     * <code>PHENIX_2_WARDEN_POLICY_RELEASE = 251;</code>
     *
     * <pre>
     *phenix -&gt; warden
     * </pre>
     */
    public static final int PHENIX_2_WARDEN_POLICY_RELEASE_VALUE = 251;
    /**
     * <code>WARDEN_2_PHENIX_POLICY_RELEASE_RESPONSE = 252;</code>
     *
     * <pre>
     *warden -&gt; phenix: release result
     * </pre>
     */
    public static final int WARDEN_2_PHENIX_POLICY_RELEASE_RESPONSE_VALUE = 252;
    /**
     * <code>PHENIX_2_WEB_POLICY_RELEASE_RESPONSE = 253;</code>
     *
     * <pre>
     *phenix -&gt; web
     * </pre>
     */
    public static final int PHENIX_2_WEB_POLICY_RELEASE_RESPONSE_VALUE = 253;
    /**
     * <code>WEB_CHECK_ENGINE_EXIST_REQUEST = 254;</code>
     *
     * <pre>
     *web --&gt; warden: request to check engine  whether exist 
     * </pre>
     */
    public static final int WEB_CHECK_ENGINE_EXIST_REQUEST_VALUE = 254;
    /**
     * <code>WEB_CHECK_ENGINE_EXIST_RESPONSE = 255;</code>
     *
     * <pre>
     *warden --&gt; web: response to check engine  whether exist
     * </pre>
     */
    public static final int WEB_CHECK_ENGINE_EXIST_RESPONSE_VALUE = 255;
    /**
     * <code>TRANSFER_2_PROBER_REQUEST = 501;</code>
     *
     * <pre>
     * FOR TRANSFER --&gt; PROBER
     * </pre>
     */
    public static final int TRANSFER_2_PROBER_REQUEST_VALUE = 501;
    /**
     * <code>PROBER_2_TRANSFER_RESPONSE = 502;</code>
     *
     * <pre>
     * prober responses for transfer's request
     * </pre>
     */
    public static final int PROBER_2_TRANSFER_RESPONSE_VALUE = 502;
    /**
     * <code>ADAM_USERSESSION = 1001;</code>
     *
     * <pre>
     *&#47;/////////////////////////////////////////////////////
     * for GATHER AND ANALYSIS ENGINE [1001, ~)
     * </pre>
     */
    public static final int ADAM_USERSESSION_VALUE = 1001;
    /**
     * <code>ADAM_STREAM = 1002;</code>
     *
     * <pre>
     *t_stream, 月表
     * </pre>
     */
    public static final int ADAM_STREAM_VALUE = 1002;
    /**
     * <code>ADAM_OPER = 1003;</code>
     *
     * <pre>
     *t_oper, 日表
     * </pre>
     */
    public static final int ADAM_OPER_VALUE = 1003;
    /**
     * <code>ADAM_TREASURY = 1004;</code>
     *
     * <pre>
     *t_treasury_log, 月表
     * </pre>
     */
    public static final int ADAM_TREASURY_VALUE = 1004;
    /**
     * <code>ADAM_TREAOPER = 1005;</code>
     *
     * <pre>
     *t_treasury_oper, 日表
     * </pre>
     */
    public static final int ADAM_TREAOPER_VALUE = 1005;
    /**
     * <code>ADAM_HBA = 1006;</code>
     *
     * <pre>
     *t_hba_log, 日表
     * </pre>
     */
    public static final int ADAM_HBA_VALUE = 1006;
    /**
     * <code>ADAM_CPSPROXY = 1007;</code>
     *
     * <pre>
     *t_proxy_log, 日表
     * </pre>
     */
    public static final int ADAM_CPSPROXY_VALUE = 1007;
    /**
     * <code>ADAM_WBA = 1008;</code>
     *
     * <pre>
     *t_wba_log, 日表
     * </pre>
     */
    public static final int ADAM_WBA_VALUE = 1008;
    /**
     * <code>ADAM_WBA_SESS = 1009;</code>
     *
     * <pre>
     *t_wba_sess, 月表
     * </pre>
     */
    public static final int ADAM_WBA_SESS_VALUE = 1009;
    /**
     * <code>ADAM_EVE = 1050;</code>
     *
     * <pre>
     *t_eve_log, 日表
     * </pre>
     */
    public static final int ADAM_EVE_VALUE = 1050;
    /**
     * <code>ADAM_IAM = 1051;</code>
     *
     * <pre>
     *t_iam_log, 日表
     * </pre>
     */
    public static final int ADAM_IAM_VALUE = 1051;
    /**
     * <code>ADAM_SMP = 1052;</code>
     *
     * <pre>
     *t_smp_log, 日表
     * </pre>
     */
    public static final int ADAM_SMP_VALUE = 1052;
    /**
     * <code>ADAM_DETOUR = 1055;</code>
     *
     * <pre>
     *t_detour_log, 日表
     * </pre>
     */
    public static final int ADAM_DETOUR_VALUE = 1055;
    /**
     * <code>ADAM_EVENT = 1061;</code>
     *
     * <pre>
     *t_event_log, 日表
     * </pre>
     */
    public static final int ADAM_EVENT_VALUE = 1061;
    /**
     * <code>ADAM_KEYANA = 1062;</code>
     *
     * <pre>
     *t_keyana_log, 月表
     * </pre>
     */
    public static final int ADAM_KEYANA_VALUE = 1062;
    /**
     * <code>ADAM_STATANA = 1063;</code>
     *
     * <pre>
     *t_statsana_log, 月表
     * </pre>
     */
    public static final int ADAM_STATANA_VALUE = 1063;
    /**
     * <code>ADAM_SUBJECT = 1064;</code>
     *
     * <pre>
     *专题分拣日志，日志中指定入库的表�?     * </pre>
     */
    public static final int ADAM_SUBJECT_VALUE = 1064;
    /**
     * <code>ADAM_DETOURANA = 1065;</code>
     *
     * <pre>
     *t_detourana_log, 日表
     * </pre>
     */
    public static final int ADAM_DETOURANA_VALUE = 1065;
    /**
     * <code>ADAM_WARN = 1066;</code>
     *
     * <pre>
     *t_warn_log, 月表
     * </pre>
     */
    public static final int ADAM_WARN_VALUE = 1066;
    /**
     * <code>ADAM_MERGER = 1067;</code>
     *
     * <pre>
     *t_merge_log 日志，归并日志表
     * </pre>
     */
    public static final int ADAM_MERGER_VALUE = 1067;
    /**
     * <code>ADAM_MERGER_RELATION = 1068;</code>
     *
     * <pre>
     *t_merge_format_relation_log 日表，归并日志与标准化日志映射表
     * </pre>
     */
    public static final int ADAM_MERGER_RELATION_VALUE = 1068;
    /**
     * <code>ADAM_STATS_RELATION = 1069;</code>
     *
     * <pre>
     *t_alarm_format_relation_log 日表，实时统计分析告警与标准化日志映射表
     * </pre>
     */
    public static final int ADAM_STATS_RELATION_VALUE = 1069;
    /**
     * <code>ADAM_FORWARD = 1071;</code>
     *
     * <pre>
     *同步用，不存日志到库�?     * </pre>
     */
    public static final int ADAM_FORWARD_VALUE = 1071;


    public final int getNumber() { return value; }

    public static ADAM_HEAD_TYPE_ENUM valueOf(int value) {
      switch (value) {
        case 1: return WEB_2_PROBER_REQUEST;
        case 2: return WEB_2_PROBER_REQUEST_VERIFY;
        case 3: return WEB_2_PROBER_RESPONSE_VERIFY;
        case 4: return WEB_2_PROBER_REQUEST_AGAIN;
        case 51: return PROBER_2_WEB_REQUEST_ACCEPT;
        case 52: return PROBER_2_WEB_RESPONSE;
        case 53: return PROBER_2_WEB_REALTIME_RESPONSE;
        case 201: return WEB_2_PHENIX_REGISTER;
        case 202: return PHENIX_2_WEB_REGISTER_RESPONSE;
        case 203: return ENGINE_2_PHENIX_PROCESS_UPDATE;
        case 204: return PHENIX_2_WEB_PROCESS_UPDATE;
        case 205: return WARDEN_2_PHENIX_HOST_UPDATE;
        case 206: return PHENIX_2_WEB_HOST_UPDATE;
        case 221: return PHENIX_2_WEB_HOST_UNAVAILABLE;
        case 222: return PHENIX_2_WEB_WARDEN_DISCONN;
        case 223: return PHENIX_2_WARDEN_CHECK;
        case 224: return WARDEN_2_PHENIX_CHECK_RESPONSE;
        case 225: return PHENIX_2_WEB_PROCESS_NOTIFY;
        case 240: return WEB_2_PHENIX_CMD_REQUEST;
        case 241: return PHENIX_2_WARDEN_CMD_REQUEST;
        case 242: return WARDEN_2_PHENIX_CMD_RESPONSE;
        case 243: return PHENIX_2_WEB_CMD_RESPONSE;
        case 250: return WEB_2_PHENIX_POLICY_RELEASE;
        case 251: return PHENIX_2_WARDEN_POLICY_RELEASE;
        case 252: return WARDEN_2_PHENIX_POLICY_RELEASE_RESPONSE;
        case 253: return PHENIX_2_WEB_POLICY_RELEASE_RESPONSE;
        case 254: return WEB_CHECK_ENGINE_EXIST_REQUEST;
        case 255: return WEB_CHECK_ENGINE_EXIST_RESPONSE;
        case 501: return TRANSFER_2_PROBER_REQUEST;
        case 502: return PROBER_2_TRANSFER_RESPONSE;
        case 1001: return ADAM_USERSESSION;
        case 1002: return ADAM_STREAM;
        case 1003: return ADAM_OPER;
        case 1004: return ADAM_TREASURY;
        case 1005: return ADAM_TREAOPER;
        case 1006: return ADAM_HBA;
        case 1007: return ADAM_CPSPROXY;
        case 1008: return ADAM_WBA;
        case 1009: return ADAM_WBA_SESS;
        case 1050: return ADAM_EVE;
        case 1051: return ADAM_IAM;
        case 1052: return ADAM_SMP;
        case 1055: return ADAM_DETOUR;
        case 1061: return ADAM_EVENT;
        case 1062: return ADAM_KEYANA;
        case 1063: return ADAM_STATANA;
        case 1064: return ADAM_SUBJECT;
        case 1065: return ADAM_DETOURANA;
        case 1066: return ADAM_WARN;
        case 1067: return ADAM_MERGER;
        case 1068: return ADAM_MERGER_RELATION;
        case 1069: return ADAM_STATS_RELATION;
        case 1071: return ADAM_FORWARD;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ADAM_HEAD_TYPE_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ADAM_HEAD_TYPE_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ADAM_HEAD_TYPE_ENUM>() {
            public ADAM_HEAD_TYPE_ENUM findValueByNumber(int number) {
              return ADAM_HEAD_TYPE_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(8);
    }

    private static final ADAM_HEAD_TYPE_ENUM[] VALUES = values();

    public static ADAM_HEAD_TYPE_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ADAM_HEAD_TYPE_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ADAM_HEAD_TYPE_ENUM)
  }

  /**
   * Protobuf enum {@code LOG_TYPE_ENUM}
   */
  public enum LOG_TYPE_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOG_UNKNOWN = 0;</code>
     *
     * <pre>
     * for all log
     * </pre>
     */
    LOG_UNKNOWN(0, 0),
    /**
     * <code>GBA_LOGON = 1;</code>
     *
     * <pre>
     * for GBA [1,10]
     * </pre>
     */
    GBA_LOGON(1, 1),
    /**
     * <code>GBA_OPER = 2;</code>
     */
    GBA_OPER(2, 2),
    /**
     * <code>GBA_LOGOFF = 3;</code>
     */
    GBA_LOGOFF(3, 3),
    /**
     * <code>NBA_LOGON = 11;</code>
     *
     * <pre>
     * for NBA [11,20]
     * </pre>
     */
    NBA_LOGON(4, 11),
    /**
     * <code>NBA_OPER = 12;</code>
     */
    NBA_OPER(5, 12),
    /**
     * <code>NBA_LOGOFF = 13;</code>
     */
    NBA_LOGOFF(6, 13),
    /**
     * <code>NBA_UPDATE = 14;</code>
     */
    NBA_UPDATE(7, 14),
    /**
     * <code>WBA_LOGON = 15;</code>
     *
     * <pre>
     * for WBA [15,18]
     * </pre>
     */
    WBA_LOGON(8, 15),
    /**
     * <code>WBA_OPER = 16;</code>
     */
    WBA_OPER(9, 16),
    /**
     * <code>WBA_LOGOFF = 17;</code>
     */
    WBA_LOGOFF(10, 17),
    /**
     * <code>WBA_UPDATE = 18;</code>
     */
    WBA_UPDATE(11, 18),
    /**
     * <code>FTP_LOG = 21;</code>
     *
     * <pre>
     * for HBA [21,30]
     * </pre>
     */
    FTP_LOG(12, 21),
    /**
     * <code>TELNET_LOG = 22;</code>
     */
    TELNET_LOG(13, 22),
    /**
     * <code>JDBC_LOG = 23;</code>
     */
    JDBC_LOG(14, 23),
    /**
     * <code>SYSLOG_LOG = 24;</code>
     */
    SYSLOG_LOG(15, 24),
    /**
     * <code>SNMPTRAP_LOG = 25;</code>
     */
    SNMPTRAP_LOG(16, 25),
    /**
     * <code>CPS_LOG = 31;</code>
     *
     * <pre>
     * for CPS [31,40]
     * </pre>
     */
    CPS_LOG(17, 31),
    /**
     * <code>USER_SESSION = 32;</code>
     */
    USER_SESSION(18, 32),
    /**
     * <code>USER_SESSION_UPDATE = 33;</code>
     */
    USER_SESSION_UPDATE(19, 33),
    /**
     * <code>LOGON = 41;</code>
     *
     * <pre>
     * for 4A [41,159]
     * </pre>
     */
    LOGON(20, 41),
    /**
     * <code>LOGOFF = 42;</code>
     */
    LOGOFF(21, 42),
    /**
     * <code>RES_OPER_LOG = 43;</code>
     */
    RES_OPER_LOG(22, 43),
    /**
     * <code>FILL_LOG = 44;</code>
     */
    FILL_LOG(23, 44),
    /**
     * <code>ACCOUNT_OPER_LOG = 45;</code>
     */
    ACCOUNT_OPER_LOG(24, 45),
    /**
     * <code>USER_OPER_LOG = 46;</code>
     */
    USER_OPER_LOG(25, 46),
    /**
     * <code>BATCH_OPER_LOG = 47;</code>
     */
    BATCH_OPER_LOG(26, 47),
    /**
     * <code>COMMON_OPER_LOG = 48;</code>
     */
    COMMON_OPER_LOG(27, 48),
    /**
     * <code>LINK_LOG = 51;</code>
     */
    LINK_LOG(28, 51),
    /**
     * <code>OPER_AUTH = 57;</code>
     */
    OPER_AUTH(29, 57),
    /**
     * <code>AUDIT_LOG = 161;</code>
     *
     * <pre>
     * for audit log
     * </pre>
     */
    AUDIT_LOG(30, 161),
    /**
     * <code>FORWARD_CPS_LOG = 240;</code>
     */
    FORWARD_CPS_LOG(31, 240),
    /**
     * <code>FORWARD_LOGON = 241;</code>
     */
    FORWARD_LOGON(32, 241),
    /**
     * <code>FORWARD_LOGOFF = 242;</code>
     */
    FORWARD_LOGOFF(33, 242),
    /**
     * <code>FORWARD_FILL_LOG = 244;</code>
     */
    FORWARD_FILL_LOG(34, 244),
    /**
     * <code>TREASURY_LOG = 245;</code>
     */
    TREASURY_LOG(35, 245),
    /**
     * <code>DETOUR_LOG = 246;</code>
     */
    DETOUR_LOG(36, 246),
    /**
     * <code>FORWARD_GBA_LOGON = 299;</code>
     */
    FORWARD_GBA_LOGON(37, 299),
    /**
     * <code>ALARM_FORMAT_LOG = 350;</code>
     */
    ALARM_FORMAT_LOG(38, 350),
    /**
     * <code>MERGE_FORMAT_LOG = 351;</code>
     */
    MERGE_FORMAT_LOG(39, 351),
    ;

    /**
     * <code>LOG_UNKNOWN = 0;</code>
     *
     * <pre>
     * for all log
     * </pre>
     */
    public static final int LOG_UNKNOWN_VALUE = 0;
    /**
     * <code>GBA_LOGON = 1;</code>
     *
     * <pre>
     * for GBA [1,10]
     * </pre>
     */
    public static final int GBA_LOGON_VALUE = 1;
    /**
     * <code>GBA_OPER = 2;</code>
     */
    public static final int GBA_OPER_VALUE = 2;
    /**
     * <code>GBA_LOGOFF = 3;</code>
     */
    public static final int GBA_LOGOFF_VALUE = 3;
    /**
     * <code>NBA_LOGON = 11;</code>
     *
     * <pre>
     * for NBA [11,20]
     * </pre>
     */
    public static final int NBA_LOGON_VALUE = 11;
    /**
     * <code>NBA_OPER = 12;</code>
     */
    public static final int NBA_OPER_VALUE = 12;
    /**
     * <code>NBA_LOGOFF = 13;</code>
     */
    public static final int NBA_LOGOFF_VALUE = 13;
    /**
     * <code>NBA_UPDATE = 14;</code>
     */
    public static final int NBA_UPDATE_VALUE = 14;
    /**
     * <code>WBA_LOGON = 15;</code>
     *
     * <pre>
     * for WBA [15,18]
     * </pre>
     */
    public static final int WBA_LOGON_VALUE = 15;
    /**
     * <code>WBA_OPER = 16;</code>
     */
    public static final int WBA_OPER_VALUE = 16;
    /**
     * <code>WBA_LOGOFF = 17;</code>
     */
    public static final int WBA_LOGOFF_VALUE = 17;
    /**
     * <code>WBA_UPDATE = 18;</code>
     */
    public static final int WBA_UPDATE_VALUE = 18;
    /**
     * <code>FTP_LOG = 21;</code>
     *
     * <pre>
     * for HBA [21,30]
     * </pre>
     */
    public static final int FTP_LOG_VALUE = 21;
    /**
     * <code>TELNET_LOG = 22;</code>
     */
    public static final int TELNET_LOG_VALUE = 22;
    /**
     * <code>JDBC_LOG = 23;</code>
     */
    public static final int JDBC_LOG_VALUE = 23;
    /**
     * <code>SYSLOG_LOG = 24;</code>
     */
    public static final int SYSLOG_LOG_VALUE = 24;
    /**
     * <code>SNMPTRAP_LOG = 25;</code>
     */
    public static final int SNMPTRAP_LOG_VALUE = 25;
    /**
     * <code>CPS_LOG = 31;</code>
     *
     * <pre>
     * for CPS [31,40]
     * </pre>
     */
    public static final int CPS_LOG_VALUE = 31;
    /**
     * <code>USER_SESSION = 32;</code>
     */
    public static final int USER_SESSION_VALUE = 32;
    /**
     * <code>USER_SESSION_UPDATE = 33;</code>
     */
    public static final int USER_SESSION_UPDATE_VALUE = 33;
    /**
     * <code>LOGON = 41;</code>
     *
     * <pre>
     * for 4A [41,159]
     * </pre>
     */
    public static final int LOGON_VALUE = 41;
    /**
     * <code>LOGOFF = 42;</code>
     */
    public static final int LOGOFF_VALUE = 42;
    /**
     * <code>RES_OPER_LOG = 43;</code>
     */
    public static final int RES_OPER_LOG_VALUE = 43;
    /**
     * <code>FILL_LOG = 44;</code>
     */
    public static final int FILL_LOG_VALUE = 44;
    /**
     * <code>ACCOUNT_OPER_LOG = 45;</code>
     */
    public static final int ACCOUNT_OPER_LOG_VALUE = 45;
    /**
     * <code>USER_OPER_LOG = 46;</code>
     */
    public static final int USER_OPER_LOG_VALUE = 46;
    /**
     * <code>BATCH_OPER_LOG = 47;</code>
     */
    public static final int BATCH_OPER_LOG_VALUE = 47;
    /**
     * <code>COMMON_OPER_LOG = 48;</code>
     */
    public static final int COMMON_OPER_LOG_VALUE = 48;
    /**
     * <code>LINK_LOG = 51;</code>
     */
    public static final int LINK_LOG_VALUE = 51;
    /**
     * <code>OPER_AUTH = 57;</code>
     */
    public static final int OPER_AUTH_VALUE = 57;
    /**
     * <code>AUDIT_LOG = 161;</code>
     *
     * <pre>
     * for audit log
     * </pre>
     */
    public static final int AUDIT_LOG_VALUE = 161;
    /**
     * <code>FORWARD_CPS_LOG = 240;</code>
     */
    public static final int FORWARD_CPS_LOG_VALUE = 240;
    /**
     * <code>FORWARD_LOGON = 241;</code>
     */
    public static final int FORWARD_LOGON_VALUE = 241;
    /**
     * <code>FORWARD_LOGOFF = 242;</code>
     */
    public static final int FORWARD_LOGOFF_VALUE = 242;
    /**
     * <code>FORWARD_FILL_LOG = 244;</code>
     */
    public static final int FORWARD_FILL_LOG_VALUE = 244;
    /**
     * <code>TREASURY_LOG = 245;</code>
     */
    public static final int TREASURY_LOG_VALUE = 245;
    /**
     * <code>DETOUR_LOG = 246;</code>
     */
    public static final int DETOUR_LOG_VALUE = 246;
    /**
     * <code>FORWARD_GBA_LOGON = 299;</code>
     */
    public static final int FORWARD_GBA_LOGON_VALUE = 299;
    /**
     * <code>ALARM_FORMAT_LOG = 350;</code>
     */
    public static final int ALARM_FORMAT_LOG_VALUE = 350;
    /**
     * <code>MERGE_FORMAT_LOG = 351;</code>
     */
    public static final int MERGE_FORMAT_LOG_VALUE = 351;


    public final int getNumber() { return value; }

    public static LOG_TYPE_ENUM valueOf(int value) {
      switch (value) {
        case 0: return LOG_UNKNOWN;
        case 1: return GBA_LOGON;
        case 2: return GBA_OPER;
        case 3: return GBA_LOGOFF;
        case 11: return NBA_LOGON;
        case 12: return NBA_OPER;
        case 13: return NBA_LOGOFF;
        case 14: return NBA_UPDATE;
        case 15: return WBA_LOGON;
        case 16: return WBA_OPER;
        case 17: return WBA_LOGOFF;
        case 18: return WBA_UPDATE;
        case 21: return FTP_LOG;
        case 22: return TELNET_LOG;
        case 23: return JDBC_LOG;
        case 24: return SYSLOG_LOG;
        case 25: return SNMPTRAP_LOG;
        case 31: return CPS_LOG;
        case 32: return USER_SESSION;
        case 33: return USER_SESSION_UPDATE;
        case 41: return LOGON;
        case 42: return LOGOFF;
        case 43: return RES_OPER_LOG;
        case 44: return FILL_LOG;
        case 45: return ACCOUNT_OPER_LOG;
        case 46: return USER_OPER_LOG;
        case 47: return BATCH_OPER_LOG;
        case 48: return COMMON_OPER_LOG;
        case 51: return LINK_LOG;
        case 57: return OPER_AUTH;
        case 161: return AUDIT_LOG;
        case 240: return FORWARD_CPS_LOG;
        case 241: return FORWARD_LOGON;
        case 242: return FORWARD_LOGOFF;
        case 244: return FORWARD_FILL_LOG;
        case 245: return TREASURY_LOG;
        case 246: return DETOUR_LOG;
        case 299: return FORWARD_GBA_LOGON;
        case 350: return ALARM_FORMAT_LOG;
        case 351: return MERGE_FORMAT_LOG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<LOG_TYPE_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<LOG_TYPE_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<LOG_TYPE_ENUM>() {
            public LOG_TYPE_ENUM findValueByNumber(int number) {
              return LOG_TYPE_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(9);
    }

    private static final LOG_TYPE_ENUM[] VALUES = values();

    public static LOG_TYPE_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private LOG_TYPE_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:LOG_TYPE_ENUM)
  }

  /**
   * Protobuf enum {@code ADAM_CTL_TYPE_ENUM}
   */
  public enum ADAM_CTL_TYPE_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADAM_CTL_REQUEST = 1;</code>
     *
     * <pre>
     * CTL request
     * </pre>
     */
    ADAM_CTL_REQUEST(0, 1),
    /**
     * <code>ADAM_CTL_RESPONSE = 2;</code>
     *
     * <pre>
     * CTL response
     * </pre>
     */
    ADAM_CTL_RESPONSE(1, 2),
    /**
     * <code>ADAM_S2C_INFO = 3;</code>
     */
    ADAM_S2C_INFO(2, 3),
    /**
     * <code>ADAM_S2C_WARN = 4;</code>
     */
    ADAM_S2C_WARN(3, 4),
    /**
     * <code>ADAM_S2C_ERROR = 5;</code>
     */
    ADAM_S2C_ERROR(4, 5),
    /**
     * <code>PHENIX_C2S_CTL_CONFIG_REQUEST = 10;</code>
     */
    PHENIX_C2S_CTL_CONFIG_REQUEST(5, 10),
    /**
     * <code>PHENIX_C2S_CTL_CHECK_REQUEST = 11;</code>
     */
    PHENIX_C2S_CTL_CHECK_REQUEST(6, 11),
    /**
     * <code>PHENIX_C2S_CTL_CHECK_ENGINE_REQUEST = 12;</code>
     */
    PHENIX_C2S_CTL_CHECK_ENGINE_REQUEST(7, 12),
    /**
     * <code>PHENIX_C2S_CTL_STATUS_REQUEST = 13;</code>
     */
    PHENIX_C2S_CTL_STATUS_REQUEST(8, 13),
    /**
     * <code>PHENIX_S2C_CTL_RESPONSE = 14;</code>
     */
    PHENIX_S2C_CTL_RESPONSE(9, 14),
    ;

    /**
     * <code>ADAM_CTL_REQUEST = 1;</code>
     *
     * <pre>
     * CTL request
     * </pre>
     */
    public static final int ADAM_CTL_REQUEST_VALUE = 1;
    /**
     * <code>ADAM_CTL_RESPONSE = 2;</code>
     *
     * <pre>
     * CTL response
     * </pre>
     */
    public static final int ADAM_CTL_RESPONSE_VALUE = 2;
    /**
     * <code>ADAM_S2C_INFO = 3;</code>
     */
    public static final int ADAM_S2C_INFO_VALUE = 3;
    /**
     * <code>ADAM_S2C_WARN = 4;</code>
     */
    public static final int ADAM_S2C_WARN_VALUE = 4;
    /**
     * <code>ADAM_S2C_ERROR = 5;</code>
     */
    public static final int ADAM_S2C_ERROR_VALUE = 5;
    /**
     * <code>PHENIX_C2S_CTL_CONFIG_REQUEST = 10;</code>
     */
    public static final int PHENIX_C2S_CTL_CONFIG_REQUEST_VALUE = 10;
    /**
     * <code>PHENIX_C2S_CTL_CHECK_REQUEST = 11;</code>
     */
    public static final int PHENIX_C2S_CTL_CHECK_REQUEST_VALUE = 11;
    /**
     * <code>PHENIX_C2S_CTL_CHECK_ENGINE_REQUEST = 12;</code>
     */
    public static final int PHENIX_C2S_CTL_CHECK_ENGINE_REQUEST_VALUE = 12;
    /**
     * <code>PHENIX_C2S_CTL_STATUS_REQUEST = 13;</code>
     */
    public static final int PHENIX_C2S_CTL_STATUS_REQUEST_VALUE = 13;
    /**
     * <code>PHENIX_S2C_CTL_RESPONSE = 14;</code>
     */
    public static final int PHENIX_S2C_CTL_RESPONSE_VALUE = 14;


    public final int getNumber() { return value; }

    public static ADAM_CTL_TYPE_ENUM valueOf(int value) {
      switch (value) {
        case 1: return ADAM_CTL_REQUEST;
        case 2: return ADAM_CTL_RESPONSE;
        case 3: return ADAM_S2C_INFO;
        case 4: return ADAM_S2C_WARN;
        case 5: return ADAM_S2C_ERROR;
        case 10: return PHENIX_C2S_CTL_CONFIG_REQUEST;
        case 11: return PHENIX_C2S_CTL_CHECK_REQUEST;
        case 12: return PHENIX_C2S_CTL_CHECK_ENGINE_REQUEST;
        case 13: return PHENIX_C2S_CTL_STATUS_REQUEST;
        case 14: return PHENIX_S2C_CTL_RESPONSE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ADAM_CTL_TYPE_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<ADAM_CTL_TYPE_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ADAM_CTL_TYPE_ENUM>() {
            public ADAM_CTL_TYPE_ENUM findValueByNumber(int number) {
              return ADAM_CTL_TYPE_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(10);
    }

    private static final ADAM_CTL_TYPE_ENUM[] VALUES = values();

    public static ADAM_CTL_TYPE_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ADAM_CTL_TYPE_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ADAM_CTL_TYPE_ENUM)
  }

  /**
   * Protobuf enum {@code SERVICE_OPERATE_ENUM}
   *
   * <pre>
   * used by web and phenix
   * </pre>
   */
  public enum SERVICE_OPERATE_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START = 1;</code>
     */
    START(0, 1),
    /**
     * <code>STOP = 2;</code>
     */
    STOP(1, 2),
    /**
     * <code>UNINSTALL = 3;</code>
     */
    UNINSTALL(2, 3),
    ;

    /**
     * <code>START = 1;</code>
     */
    public static final int START_VALUE = 1;
    /**
     * <code>STOP = 2;</code>
     */
    public static final int STOP_VALUE = 2;
    /**
     * <code>UNINSTALL = 3;</code>
     */
    public static final int UNINSTALL_VALUE = 3;


    public final int getNumber() { return value; }

    public static SERVICE_OPERATE_ENUM valueOf(int value) {
      switch (value) {
        case 1: return START;
        case 2: return STOP;
        case 3: return UNINSTALL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SERVICE_OPERATE_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SERVICE_OPERATE_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SERVICE_OPERATE_ENUM>() {
            public SERVICE_OPERATE_ENUM findValueByNumber(int number) {
              return SERVICE_OPERATE_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(11);
    }

    private static final SERVICE_OPERATE_ENUM[] VALUES = values();

    public static SERVICE_OPERATE_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SERVICE_OPERATE_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SERVICE_OPERATE_ENUM)
  }

  /**
   * Protobuf enum {@code SERVICE_STATUS_ENUM}
   */
  public enum SERVICE_STATUS_ENUM
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STATUS_RUNNING = 1;</code>
     */
    STATUS_RUNNING(0, 1),
    /**
     * <code>STATUS_STOP = 2;</code>
     */
    STATUS_STOP(1, 2),
    /**
     * <code>STATUS_ZOMBIE = 3;</code>
     */
    STATUS_ZOMBIE(2, 3),
    ;

    /**
     * <code>STATUS_RUNNING = 1;</code>
     */
    public static final int STATUS_RUNNING_VALUE = 1;
    /**
     * <code>STATUS_STOP = 2;</code>
     */
    public static final int STATUS_STOP_VALUE = 2;
    /**
     * <code>STATUS_ZOMBIE = 3;</code>
     */
    public static final int STATUS_ZOMBIE_VALUE = 3;


    public final int getNumber() { return value; }

    public static SERVICE_STATUS_ENUM valueOf(int value) {
      switch (value) {
        case 1: return STATUS_RUNNING;
        case 2: return STATUS_STOP;
        case 3: return STATUS_ZOMBIE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<SERVICE_STATUS_ENUM>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<SERVICE_STATUS_ENUM>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<SERVICE_STATUS_ENUM>() {
            public SERVICE_STATUS_ENUM findValueByNumber(int number) {
              return SERVICE_STATUS_ENUM.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return AdamEnum.getDescriptor().getEnumTypes().get(12);
    }

    private static final SERVICE_STATUS_ENUM[] VALUES = values();

    public static SERVICE_STATUS_ENUM valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private SERVICE_STATUS_ENUM(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:SERVICE_STATUS_ENUM)
  }


  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017adam_enum.proto\022\004adam*8\n\020WEB_SERVICE_E" +
      "NUM\022\006\n\002FA\020\001\022\007\n\003SMP\020\002\022\010\n\004ISMP\020\004\022\t\n\004ADAM\020\200" +
      "\010*\256\002\n\020ENGINE_TYPE_ENUM\022\013\n\007UNKNOWN\020\000\022\007\n\003N" +
      "BA\020\001\022\013\n\007SYSLOGD\020\002\022\010\n\004FTPD\020\003\022\013\n\007TELNETD\020\004" +
      "\022\t\n\005JDBCD\020\005\022\007\n\003GBA\020\006\022\007\n\003CPS\020\007\022\007\n\003IBA\020\010\022\n" +
      "\n\006FILTER\020\t\022\007\n\003NDE\020\n\022\t\n\005ASCII\020\013\022\n\n\006PROBER" +
      "\020\014\022\n\n\006WARDEN\020\r\022\n\n\006PHENIX\020\016\022\007\n\003EVE\020\017\022\007\n\003W" +
      "BA\020\020\022\014\n\010SNMPTRAP\020\021\022\n\n\006DETOUR\020\022\022\t\n\005EVENT\020" +
      "\023\022\t\n\005STATS\020\024\022\n\n\006MERGER\020\025\022\006\n\002PB\020\026\022\007\n\003CBA\020" +
      "\027\022\t\n\005ALERT\020\030\022\014\n\010TRANSFER\020\031*\\\n\022ADAM_PROTO",
      "COL_ENUM\022\010\n\004SSH1\020\001\022\010\n\004SSH2\020\002\022\n\n\006TELNET\020\004" +
      "\022\007\n\003FTP\020\010\022\010\n\004SFTP\020\020\022\010\n\004HTTP\020 \022\t\n\005HTTPS\020@" +
      "*\224\001\n\023ADAM_LOG_LEVEL_ENUM\022\016\n\nKERN_EMERG\020\001" +
      "\022\016\n\nKERN_ALERT\020\002\022\r\n\tKERN_CRIT\020\003\022\014\n\010KERN_" +
      "ERR\020\004\022\020\n\014KERN_WARNING\020\005\022\017\n\013KERN_NOTICE\020\006" +
      "\022\r\n\tKERN_INFO\020\007\022\016\n\nKERN_DEBUG\020\010*m\n\024ADAM_" +
      "ORDER_TYPE_ENUM\022\022\n\016ORDER_SEQUENCE\020\001\022\020\n\014O" +
      "RDER_SCRIPT\020\002\022\016\n\nORDER_HTTP\020\003\022\017\n\013ORDER_H" +
      "TTPS\020\004\022\016\n\nORDER_JDBC\020\005*B\n\022ADAM_ENCODING_" +
      "ENUM\022\016\n\nADAM_ASCII\020\001\022\016\n\nADAM_UTF_8\020\002\022\014\n\010",
      "ADAM_GBK\020\003*\223\002\n\017ANA_POLICY_TYPE\022\021\n\rFILTER" +
      "_POLICY\020\001\022\022\n\016SUBJECT_POLICY\020\002\022\020\n\014EVENT_P" +
      "OLICY\020\003\022\020\n\014STATS_POLICY\020\004\022\021\n\rDETOUR_POLI" +
      "CY\020\005\022\021\n\rMERGER_POLICY\020\006\022\025\n\021NBA_ENCODE_PO" +
      "LICY\020\n\022\025\n\021GBA_ENCODE_POLICY\020\013\022\030\n\024SYSLOG_" +
      "ENCODE_POLICY\020\014\022\025\n\021FTP_ENCODE_POLICY\020\r\022\030" +
      "\n\024TELNET_ENCODE_POLICY\020\016\022\026\n\022JDBC_ENCODE_" +
      "POLICY\020\017*&\n\tDIRECTION\022\013\n\007REQUEST\020\000\022\014\n\010RE" +
      "SPONSE\020\001*\302\013\n\023ADAM_HEAD_TYPE_ENUM\022\030\n\024WEB_" +
      "2_PROBER_REQUEST\020\001\022\037\n\033WEB_2_PROBER_REQUE",
      "ST_VERIFY\020\002\022 \n\034WEB_2_PROBER_RESPONSE_VER" +
      "IFY\020\003\022\036\n\032WEB_2_PROBER_REQUEST_AGAIN\020\004\022\037\n" +
      "\033PROBER_2_WEB_REQUEST_ACCEPT\0203\022\031\n\025PROBER" +
      "_2_WEB_RESPONSE\0204\022\"\n\036PROBER_2_WEB_REALTI" +
      "ME_RESPONSE\0205\022\032\n\025WEB_2_PHENIX_REGISTER\020\311" +
      "\001\022#\n\036PHENIX_2_WEB_REGISTER_RESPONSE\020\312\001\022#" +
      "\n\036ENGINE_2_PHENIX_PROCESS_UPDATE\020\313\001\022 \n\033P" +
      "HENIX_2_WEB_PROCESS_UPDATE\020\314\001\022 \n\033WARDEN_" +
      "2_PHENIX_HOST_UPDATE\020\315\001\022\035\n\030PHENIX_2_WEB_" +
      "HOST_UPDATE\020\316\001\022\"\n\035PHENIX_2_WEB_HOST_UNAV",
      "AILABLE\020\335\001\022 \n\033PHENIX_2_WEB_WARDEN_DISCON" +
      "N\020\336\001\022\032\n\025PHENIX_2_WARDEN_CHECK\020\337\001\022#\n\036WARD" +
      "EN_2_PHENIX_CHECK_RESPONSE\020\340\001\022 \n\033PHENIX_" +
      "2_WEB_PROCESS_NOTIFY\020\341\001\022\035\n\030WEB_2_PHENIX_" +
      "CMD_REQUEST\020\360\001\022 \n\033PHENIX_2_WARDEN_CMD_RE" +
      "QUEST\020\361\001\022!\n\034WARDEN_2_PHENIX_CMD_RESPONSE" +
      "\020\362\001\022\036\n\031PHENIX_2_WEB_CMD_RESPONSE\020\363\001\022 \n\033W" +
      "EB_2_PHENIX_POLICY_RELEASE\020\372\001\022#\n\036PHENIX_" +
      "2_WARDEN_POLICY_RELEASE\020\373\001\022,\n\'WARDEN_2_P" +
      "HENIX_POLICY_RELEASE_RESPONSE\020\374\001\022)\n$PHEN",
      "IX_2_WEB_POLICY_RELEASE_RESPONSE\020\375\001\022#\n\036W" +
      "EB_CHECK_ENGINE_EXIST_REQUEST\020\376\001\022$\n\037WEB_" +
      "CHECK_ENGINE_EXIST_RESPONSE\020\377\001\022\036\n\031TRANSF" +
      "ER_2_PROBER_REQUEST\020\365\003\022\037\n\032PROBER_2_TRANS" +
      "FER_RESPONSE\020\366\003\022\025\n\020ADAM_USERSESSION\020\351\007\022\020" +
      "\n\013ADAM_STREAM\020\352\007\022\016\n\tADAM_OPER\020\353\007\022\022\n\rADAM" +
      "_TREASURY\020\354\007\022\022\n\rADAM_TREAOPER\020\355\007\022\r\n\010ADAM" +
      "_HBA\020\356\007\022\022\n\rADAM_CPSPROXY\020\357\007\022\r\n\010ADAM_WBA\020" +
      "\360\007\022\022\n\rADAM_WBA_SESS\020\361\007\022\r\n\010ADAM_EVE\020\232\010\022\r\n" +
      "\010ADAM_IAM\020\233\010\022\r\n\010ADAM_SMP\020\234\010\022\020\n\013ADAM_DETO",
      "UR\020\237\010\022\017\n\nADAM_EVENT\020\245\010\022\020\n\013ADAM_KEYANA\020\246\010" +
      "\022\021\n\014ADAM_STATANA\020\247\010\022\021\n\014ADAM_SUBJECT\020\250\010\022\023" +
      "\n\016ADAM_DETOURANA\020\251\010\022\016\n\tADAM_WARN\020\252\010\022\020\n\013A" +
      "DAM_MERGER\020\253\010\022\031\n\024ADAM_MERGER_RELATION\020\254\010" +
      "\022\030\n\023ADAM_STATS_RELATION\020\255\010\022\021\n\014ADAM_FORWA" +
      "RD\020\257\010*\302\005\n\rLOG_TYPE_ENUM\022\017\n\013LOG_UNKNOWN\020\000" +
      "\022\r\n\tGBA_LOGON\020\001\022\014\n\010GBA_OPER\020\002\022\016\n\nGBA_LOG" +
      "OFF\020\003\022\r\n\tNBA_LOGON\020\013\022\014\n\010NBA_OPER\020\014\022\016\n\nNB" +
      "A_LOGOFF\020\r\022\016\n\nNBA_UPDATE\020\016\022\r\n\tWBA_LOGON\020" +
      "\017\022\014\n\010WBA_OPER\020\020\022\016\n\nWBA_LOGOFF\020\021\022\016\n\nWBA_U",
      "PDATE\020\022\022\013\n\007FTP_LOG\020\025\022\016\n\nTELNET_LOG\020\026\022\014\n\010" +
      "JDBC_LOG\020\027\022\016\n\nSYSLOG_LOG\020\030\022\020\n\014SNMPTRAP_L" +
      "OG\020\031\022\013\n\007CPS_LOG\020\037\022\020\n\014USER_SESSION\020 \022\027\n\023U" +
      "SER_SESSION_UPDATE\020!\022\t\n\005LOGON\020)\022\n\n\006LOGOF" +
      "F\020*\022\020\n\014RES_OPER_LOG\020+\022\014\n\010FILL_LOG\020,\022\024\n\020A" +
      "CCOUNT_OPER_LOG\020-\022\021\n\rUSER_OPER_LOG\020.\022\022\n\016" +
      "BATCH_OPER_LOG\020/\022\023\n\017COMMON_OPER_LOG\0200\022\014\n" +
      "\010LINK_LOG\0203\022\r\n\tOPER_AUTH\0209\022\016\n\tAUDIT_LOG\020" +
      "\241\001\022\024\n\017FORWARD_CPS_LOG\020\360\001\022\022\n\rFORWARD_LOGO" +
      "N\020\361\001\022\023\n\016FORWARD_LOGOFF\020\362\001\022\025\n\020FORWARD_FIL",
      "L_LOG\020\364\001\022\021\n\014TREASURY_LOG\020\365\001\022\017\n\nDETOUR_LO" +
      "G\020\366\001\022\026\n\021FORWARD_GBA_LOGON\020\253\002\022\025\n\020ALARM_FO" +
      "RMAT_LOG\020\336\002\022\025\n\020MERGE_FORMAT_LOG\020\337\002*\251\002\n\022A" +
      "DAM_CTL_TYPE_ENUM\022\024\n\020ADAM_CTL_REQUEST\020\001\022" +
      "\025\n\021ADAM_CTL_RESPONSE\020\002\022\021\n\rADAM_S2C_INFO\020" +
      "\003\022\021\n\rADAM_S2C_WARN\020\004\022\022\n\016ADAM_S2C_ERROR\020\005" +
      "\022!\n\035PHENIX_C2S_CTL_CONFIG_REQUEST\020\n\022 \n\034P" +
      "HENIX_C2S_CTL_CHECK_REQUEST\020\013\022\'\n#PHENIX_" +
      "C2S_CTL_CHECK_ENGINE_REQUEST\020\014\022!\n\035PHENIX" +
      "_C2S_CTL_STATUS_REQUEST\020\r\022\033\n\027PHENIX_S2C_",
      "CTL_RESPONSE\020\016*:\n\024SERVICE_OPERATE_ENUM\022\t" +
      "\n\005START\020\001\022\010\n\004STOP\020\002\022\r\n\tUNINSTALL\020\003*M\n\023SE" +
      "RVICE_STATUS_ENUM\022\022\n\016STATUS_RUNNING\020\001\022\017\n" +
      "\013STATUS_STOP\020\002\022\021\n\rSTATUS_ZOMBIE\020\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
